version: "3.9"

services:
  routy-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: routy_dashboard_app
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production


